package com.`kevin-nation`.minecraft

import com.`kevin-nation`.minecraft.builder.BookBuilder
import com.`kevin-nation`.minecraft.builder.CategoryBuilder
import com.`kevin-nation`.minecraft.builder.itemFromResourceName
import de.maxanier.guideapi.api.GuideBook
import de.maxanier.guideapi.api.IGuideBook
import de.maxanier.guideapi.api.impl.Book
import net.minecraft.item.ItemStack
import net.minecraft.item.Items
import net.minecraft.item.crafting.Ingredient
import net.minecraft.util.text.TextFormatting.*

@GuideBook
class GuideBook : IGuideBook {

    override fun buildBook(): Book = BookBuilder.buildBook(
        resourceId = "kevin-nation:guide-book",
        author = "Joob",
        displayName = "Guide book",
        header = "Welcome to Kevin Nation",
        title = "Kevin Nation Guide Book",
        spawnWithBook = true,
    ) {
        category(ModItems.WAYSTONE, "Waystones") {
            entry(ModItems.WAYSTONE, "What are waystones?") {
                itemStackPage(Ingredient.fromStacks(
                    ItemStack { itemFromResourceName(ModItems.WAYSTONE) },
                    ItemStack { itemFromResourceName(ModItems.MOSSY_WAYSTONE) },
                    ItemStack { itemFromResourceName(ModItems.SANDY_WAYSTONE) },
                ), """
                    | A Waystone is the way Kevins can travel fast across the Kevin Nation.
                    |
                    | Right clicking on one will activate it. If already active, right clicking will show you all previously activated Waystones and allow you to teleport to them instantly!
                """)
                pagesWithText("Note that traveling to a Waystone across dimensions is possible but it will cost you levels so use it wisely!")
            }
            entry(Items.FILLED_MAP, "Where can I find Waystones?") {
                pagesWithText("""
                    | You can find your first two Waystones in the spawn house and in the Shopping district. Try activating them and teleport between them!
                    |
                    | You can also find Waystones scattered across Kevin Nation. They are usually found on top of abandoned towers along with some treasure so activate as many as you can.
                """)

                imagePage(guiTexture("tower"), "    An abandoned tower")
            }
            entry(Items.CRAFTING_TABLE, "Can I have my own?") {
                pagesWithText("""
                    | Waystones can be destroyed and picked up like most blocks.
                    | 
                    | If you find Waystones in the wild though, they are most likely being used by other Kevins too so avoid taking those.
                    | 
                    | If you find a Waystone without an autogenerated name (you will know when you see it), please destroy it and place it again giving it a descriptive name. Maybe use the biome it is in and the coordinates (River 999, 555 for example).
                    | 
                    | You can also craft your own Waystones:
                """)
                recipePage(ModItems.WAYSTONE)
                recipePage(ModItems.WARP_STONE)
            }
            entry(ModItems.WARP_SCROLL, "Can I only teleport from Waystones?") {
                page {
                    paragraph("There may be times when you want to teleport to a Waystone but you are not standing next to one (after a long and dangerous mining expedition to the Nether for example).")

                    paragraph("Thankfully there are 4 ways to teleport to a Waystone from anywhere in the world:")
                }
                itemStackPage(ModItems.WARP_SCROLL) {
                    paragraph("Warp Scroll", BOLD, BLUE)
                    paragraph("A warp scroll is a one-use item which will teleport you to a Waystone of your choice.")
                }
                recipePage(ModItems.WARP_SCROLL)

                itemStackPage(ModItems.RETURN_SCROLL) {
                    paragraph("Return Scroll", BOLD, BLUE)
                    paragraph("A return scroll works like a Warp Scroll but will return you to your last used Waystone.")
                }
                recipePage(ModItems.RETURN_SCROLL)

                itemStackPage(ModItems.BOUND_SCROLL) {
                    paragraph("Return Scroll (Bound)", BOLD, BLUE)
                    paragraph("A bound return scroll works like a normal Return Scroll but it will return you to a predefined Waystone.")
                }
                recipePage(ModItems.BOUND_SCROLL)

                itemStackPage(ModItems.WARP_STONE) {
                    paragraph("Warp Stone", BOLD, BLUE)
                    paragraph("A warp stone is like a portable Waystone. You can activate it at any point but it has a cooldown during which you won't be able to use it again so use it wisely. It is also an ingredient of the Waystone.")
                }
                recipePage(ModItems.WARP_STONE)
            }
        }
        category(ModItems.COIN_DOLLAR, "Shops") {
            entry(ModItems.MONEY_BAG_RICH, "Currency") {
                pagesWithText(Items.DIAMOND, """
                    | The currency here at Kevin Nation is Cat Treats (naturally).
                    |
                    | You can use Cat Treats to buy resources from shops other Kevins have set up around the Shopping district.
                    |
                    | You can get Cat Treats by trading diamonds in the Bank building at the shopping center.
                """)
            }
            entry(ModItems.WALLET, "Wallets") {
                pagesWithText(ModItems.WALLET, """
                    | Wallets store currency. You should already have been given a wallet when you joined.
                    | 
                    | When you trade diamonds for Cat Treats at the bank, make sure you have a wallet in your inventory to store them.
                    |
                    | Wallets are also used when you create your own shop. They are an ingredient to the Bank item which is needed to collect Cat Treats from customers.
                    | 
                    | You can get more free wallets at the Bank building in the Shopping district when you need them.
                """)
            }
            entry(ModItems.MONEY_BAG_CHEAP, "Shopping") {
                pagesWithText("""
                   | Spread around our Shopping District, you will find the various shops that Kevins have created.
                   |  
                   | If you have a wallet with enough Cat Treats present in your inventory, you can shop for various items listed in the shop by right clicking on any of the trading posts on display.
                """)
                itemStackPage(ModItems.TRADING_POST, "The trading post will display the item for sale. You can view the price by looking at the trading post and more details about the item by sneaking (default Shift)")
            }
            entry(ModItems.TRADING_POST, "Setting up shop") {
                pagesWithText("""
                    | Setting up your own shop is very easy. First you will need to get yourself a free wallet from the Bank building in the Shopping center.
                    | 
                    | Next, you will need to craft a 'Bank' item, a few 'Network Cables', a 'Security Wrench' as well as as many trading posts as items you intend to sell:
                """)
                recipePage(ModRecipes.BANK_RECIPE)
                recipePage(ModRecipes.GOLD_CHIP)
                recipePage(ModRecipes.NETWORK_CABLE)
                recipePage(ModRecipes.NETWORK_CABLE_OPAQUE)
                recipePage(ModRecipes.SECURITY_WRENCH)
                recipePage(ModRecipes.TRADING_POST)
                pagesWithText("""
                   | Once you have these items constructed, you will need to place a trading post on top of a network cable block and then put as many network cables as you need to connect it to your Bank block.
                   |  
                   | You can run multiple network cables around your shop to the same bank so you can sell multiple items.
                   |
                   | The bank will store your profits which you can later collect by right clicking on it and placing your wallet to make a withdrawal.
                   |  
                   | Don't worry! Your bank and all the gear mentioned above are safe as only you can modify them. This is where the Security Wrench comes in.
                """)
                itemStackPage(ModItems.SECURITY_WRENCH, """
                        | All the items mentioned so far can only be removed or modified using a Security Wrench by you and only you.
                        |
                        | You have to use the Security Wrench to configure what you sell on the trading post.
                """)
                itemStackPage(ModItems.TRADING_POST, "The trading post will display the item you are selling and its price. By sneaking when looking at the trading post, more information will be displayed (useful for things like enchanting books).")

                imagePage(guiTexture("trading_post"), "Trading post UI", true)

                pagesWithText("""
                    | At the top of the trading post UI, you can select whether you are selling or buying items. If you decide you want to buy something, you can set a price but you have to make sure that the bank connected to the trading post has enough Cat Treats for each purchase.
                    |
                    | The middle slot at the top of the UI is where you place the item you are selling/buying.
                    | 
                    | You can use the button on the top right to announce to the server what you are selling/buying.
                    | 
                    | Below that you can choose an item quantity and price for that quantity. For example you can decide to sell 1 stack (64) of honey blocks for 200 Cat Treats (equivalent to 2 diamonds). You will then set the amount to 64 and the price to 200. There are shortcuts to modify the price by bigger quantities to make it easy to set. You can see the shortcuts by hovering over the red icon on the top left of the ui.
                    | 
                    | Lastly, if you are selling instead of buying, you can place as many items as you have available for sale in the inventory at the bottom of the UI.
                """)
            }
        }
        category(Items.FILLED_MAP, "Maps") {
            wip()
        }
        category(ModItems.BANNER_RALLY_GUARDS, "Claiming Land") {
            wip()
        }
        category(ModItems.SUPPLY_CHEST_DEPLOYER, "Colonies") {
            wip()
        }
        category(ModItems.GRAVESTONE, "Graves") {
            wip()
        }
        category(Items.NETHERITE_CHESTPLATE, "Cosmetic Armour") {
            wip()
        }
        category(ModItems.DANK_7, "Dank Storage") {
            wip()
        }
        category(ModItems.WATER_WHEEL, "Create") {
            wip()
        }
        category(ModItems.STAMP, "Ender Mail") {
            wip()
        }
        category(ModItems.PAPER_LANTERN, "Fairy lights/Additional Lights") {
            wip()
        }
        category(ModItems.GOLDEN_HOPPER, "Miscellaneous") {
            wip()
        }
    }

    private fun CategoryBuilder.wip() = entry(ModItems.IRON_SCAFFOLD, "Work In Progress. More Pages coming soon.") {
        itemStackPage(ModItems.IRON_SCAFFOLD, "Please check back soon for more information.")
    }
}